[[redirects]]
  from = "/p/:pid/:bid"
  to = "/p/[pid]/[bid].html"
  status = 200
  force = true

[[redirects]]
  from = "/p/:pid"
  to = "/p/[pid].html"
  status = 200
  force = true

[[redirects]]
  from = "/debug/:aid/:bid"
  to = "/debug/[aid]/[bid].html"
  status = 200
  force = true

[[redirects]]
  from = "/debug/:aid"
  to = "/debug/[aid].html"
  status = 200
  force = true
