[[redirects]]
  from = "/p/tdu/*"
  to = "/p/[pid]/[bid].html"
  status = 200
  force = true
[[redirects]]
  from = "/p/nue/*"
  to = "/p/[pid]/[bid].html"
  status = 200
  force = true
[[redirects]]
  from = "/p/*"
  to = "/p/[pid].html"
  status = 200
  force = true